/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Metrics */
        get: operations["read_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Places */
        get: operations["search_places_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Magic Link */
        post: operations["request_magic_link_api_auth_magic_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_auth_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/passport/{username}/card.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Share Card */
        get: operations["read_share_card_api_passport__username__card_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profile */
        get: operations["read_profile_api_users__username__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/passport/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Passport */
        get: operations["read_passport_api_passport__username__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Place */
        get: operations["read_place_api_places__place_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{place_id}/etymology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Correct Etymology
         * @description File a correction. Held for review, never applied on the spot.
         *
         *     An account is required because the contributor credit is the point: a
         *     correction is somebody putting their name to a claim about the world.
         */
        post: operations["correct_etymology_api_places__place_id__etymology_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discoveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read My Discoveries
         * @description Whatever the caller has claimed, account or not.
         *
         *     A guest has to be able to read their own claim: it is the only way the
         *     deadline survives a reload, and the only way the interface can explain the
         *     claim control instead of offering a second one. Not a 401 either way -
         *     a visitor who has claimed nothing has claimed nothing.
         */
        get: operations["read_my_discoveries_api_discoveries_get"];
        put?: never;
        /**
         * Create Discovery
         * @description Claiming is the one write that does not require an account.
         */
        post: operations["create_discovery_api_discoveries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/puzzle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Puzzle
         * @description Today's puzzle and this player's progress. Null on a day without one.
         */
        get: operations["read_puzzle_api_puzzle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/puzzle/{puzzle_id}/guess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Guess Puzzle
         * @description Guess, and hear how close it came. No account needed to play.
         */
        post: operations["guess_puzzle_api_puzzle__puzzle_id__guess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/puzzle/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Puzzle Archive
         * @description Puzzles that have been and gone, and how they went.
         *
         *     Account-gated, per Addendum A. No answers: it is for replaying, not for
         *     reading ahead. The refusal says what an account is for here rather than
         *     the generic "sign in", because the archive is a reason to have one.
         */
        get: operations["read_puzzle_archive_api_puzzle_archive_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/{job}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Scheduled Job Get
         * @description Vercel's scheduler invokes with GET. See run_scheduled_job.
         */
        get: operations["run_scheduled_job_get_api_cron__job__get"];
        put?: never;
        /**
         * Run Scheduled Job
         * @description Run one scheduled job. For platforms with no long-running process.
         *
         *     Declared for GET as well, because Vercel's scheduler invokes with GET and
         *     does not follow redirects: POST alone would deploy cleanly and never run
         *     once. Two endpoints rather than one multi-method route, because FastAPI
         *     gives both methods of a multi-method route the same operation id, and the
         *     generated frontend types then fail to compile on a duplicate identifier.
         *
         *     Also the way to force a job by hand, which is what makes a plan with
         *     once-a-day cron usable: a contest can be resolved on demand rather than
         *     waited for. Cron delivery is best effort and may miss a run or repeat one,
         *     which is safe here: each job takes a Redis lock and each is idempotent.
         *
         *     Fails closed on an unset secret. These endpoints resolve contests and
         *     release claims, so an open one would be a way to force either at will.
         */
        post: operations["run_scheduled_job_api_cron__job__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/viewport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Viewport */
        get: operations["read_viewport_api_viewport_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Bookmark */
        post: operations["add_bookmark_api_bookmarks__place_id__post"];
        /** Remove Bookmark */
        delete: operations["remove_bookmark_api_bookmarks__place_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Bookmarks */
        get: operations["read_bookmarks_api_bookmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Proposal */
        post: operations["create_proposal_api_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cast Vote */
        post: operations["cast_vote_api_votes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contests/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Contest */
        get: operations["read_contest_api_contests__place_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Activity */
        get: operations["read_activity_api_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityResponse
         * @description What the chrome needs to show a reason to return, in one request.
         */
        ActivityResponse: {
            /** Contests Closing Soon */
            contests_closing_soon: number;
            /** Streak Days */
            streak_days: number | null;
            /** Streak At Risk */
            streak_at_risk: boolean;
        };
        /** ArchiveEntry */
        ArchiveEntry: {
            /** Puzzle Id */
            puzzle_id: number;
            /** Number */
            number: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Solved */
            solved: boolean;
            /** Guesses */
            guesses: number;
        };
        /** ArchiveResponse */
        ArchiveResponse: {
            /** Puzzles */
            puzzles: components["schemas"]["ArchiveEntry"][];
        };
        /** BookmarksResponse */
        BookmarksResponse: {
            /** Bookmarks */
            bookmarks: components["schemas"]["SavedPlaceResponse"][];
        };
        /** ClaimRequest */
        ClaimRequest: {
            /** Place Id */
            place_id: number;
            /** Caption */
            caption: string;
            /** Etymology */
            etymology?: string | null;
        };
        /** ContestBoard */
        ContestBoard: {
            /** Place Id */
            place_id: number;
            /** Nickname */
            nickname: string | null;
            /** Leading Candidate */
            leading_candidate: string | null;
            /** Closes At */
            closes_at: string | null;
            /** Reopens At */
            reopens_at: string | null;
            /** Quorum */
            quorum: number;
            /** Proposals */
            proposals: components["schemas"]["ProposalResponse"][];
        };
        /** CorrectionRequest */
        CorrectionRequest: {
            /** Text */
            text: string;
        };
        /** CorrectionResponse */
        CorrectionResponse: {
            /** Id */
            id: number;
            /** Place Id */
            place_id: number;
            /** Status */
            status: string;
        };
        /** CronResult */
        CronResult: {
            /** Job */
            job: string;
            /** Changed */
            changed: number;
        };
        /** DiscoveryResponse */
        DiscoveryResponse: {
            /** Id */
            id: number;
            /** Place Id */
            place_id: number;
            /** Finder */
            finder: string;
            /** Caption */
            caption: string;
            /** Expires At */
            expires_at?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** GuessRequest */
        GuessRequest: {
            /** Place Id */
            place_id: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness of the API and the backing services it cannot work without.
         */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Db */
            db: boolean;
            /** Redis */
            redis: boolean;
        };
        /** MagicLinkRequest */
        MagicLinkRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Me */
        Me: {
            /** Username */
            username: string;
        };
        /** PassportResponse */
        PassportResponse: {
            /** Username */
            username: string;
            /** Discoveries */
            discoveries: number;
            /** First Finds */
            first_finds: number;
            /** Countries */
            countries: {
                [key: string]: number;
            };
            /** Completion */
            completion: {
                [key: string]: number;
            };
            /** Streak Days */
            streak_days: number;
            /** Streak At Risk */
            streak_at_risk: boolean;
        };
        /** PlaceDetail */
        PlaceDetail: {
            /** Id */
            id: number;
            /** Geonames Id */
            geonames_id: number;
            /** Name */
            name: string;
            /** Feature Class */
            feature_class: string;
            /** Feature Code */
            feature_code: string;
            /** Country Code */
            country_code: string | null;
            /** Tier */
            tier: number;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Etymology */
            etymology: string | null;
            /** Etymology Confidence */
            etymology_confidence: string | null;
            /** Etymology Source */
            etymology_source: string | null;
            /** Name Language */
            name_language: string | null;
            /** Claimed By */
            claimed_by: string | null;
            /** Bookmarked */
            bookmarked: boolean;
            /** Eligibility */
            eligibility: string;
            /** Eligibility Reason */
            eligibility_reason: string | null;
        };
        /** Profile */
        Profile: {
            /** Username */
            username: string;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
            /** Discoveries */
            discoveries: number;
        };
        /** ProposalRequest */
        ProposalRequest: {
            /** Place Id */
            place_id: number;
            /** Text */
            text: string;
        };
        /** ProposalResponse */
        ProposalResponse: {
            /** Id */
            id: number;
            /** Text */
            text: string;
            /** Agree */
            agree: number;
            /** Disagree */
            disagree: number;
            /** Score */
            score: number;
            /** Is Incumbent */
            is_incumbent: boolean;
            /**
             * Is Yours
             * @default false
             */
            is_yours: boolean;
        };
        /** PuzzleAnswerResponse */
        PuzzleAnswerResponse: {
            /** Place Id */
            place_id: number;
            /** Name */
            name: string;
            /** Country Code */
            country_code: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Claimed By */
            claimed_by: string | null;
        };
        /** PuzzleGuessResponse */
        PuzzleGuessResponse: {
            /** Place Id */
            place_id: number;
            /** Name */
            name: string;
            /** Distance Km */
            distance_km: number;
            /** Bearing */
            bearing: number;
            /** Arrow */
            arrow: string;
            /** Band */
            band: string;
            /** Proximity */
            proximity: number;
        };
        /** PuzzlePinResponse */
        PuzzlePinResponse: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** PuzzleStateResponse */
        PuzzleStateResponse: {
            /** Puzzle Id */
            puzzle_id: number;
            /** Number */
            number: number;
            /** Clues */
            clues: string[];
            /** Guesses */
            guesses: components["schemas"]["PuzzleGuessResponse"][];
            /** Solved */
            solved: boolean;
            /** Complete */
            complete: boolean;
            /** Remaining */
            remaining: number;
            pin: components["schemas"]["PuzzlePinResponse"] | null;
            answer: components["schemas"]["PuzzleAnswerResponse"] | null;
            /** Share Grid */
            share_grid: string;
            /** Streak */
            streak: number;
        };
        /** SavedPlaceResponse */
        SavedPlaceResponse: {
            /** Place Id */
            place_id: number;
            /** Name */
            name: string;
            /** Country Code */
            country_code: string | null;
            /** Lon */
            lon: number;
            /** Lat */
            lat: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["SearchResult"][];
        };
        /**
         * SearchResult
         * @description One gazetteer hit, with whether anyone has already claimed it.
         */
        SearchResult: {
            /** Id */
            id: number;
            /** Geonames Id */
            geonames_id: number;
            /** Name */
            name: string;
            /** Feature Class */
            feature_class: string;
            /** Feature Code */
            feature_code: string;
            /** Country Code */
            country_code: string | null;
            /** Admin1 */
            admin1: string | null;
            /** Tier */
            tier: number;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Claimed By */
            claimed_by: string | null;
        };
        /** SessionRequest */
        SessionRequest: {
            /** Token */
            token: string;
        };
        /** UserDiscoveriesResponse */
        UserDiscoveriesResponse: {
            /** Discoveries */
            discoveries: components["schemas"]["UserDiscoveryResponse"][];
        };
        /** UserDiscoveryResponse */
        UserDiscoveryResponse: {
            /** Id */
            id: number;
            /** Place Id */
            place_id: number;
            /** Place Name */
            place_name: string;
            /** Country Code */
            country_code: string | null;
            /** Caption */
            caption: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ViewportFeature */
        ViewportFeature: {
            /** Lon */
            lon: number;
            /** Lat */
            lat: number;
            /** Count */
            count: number;
            /** Place Id */
            place_id: number | null;
            /** Name */
            name: string | null;
            /** Finder */
            finder: string | null;
            /** Country Code */
            country_code: string | null;
            /** Score */
            score: number;
        };
        /** ViewportResponse */
        ViewportResponse: {
            /** Band */
            band: string;
            /** Features */
            features: components["schemas"]["ViewportFeature"][];
            /** Nicknames */
            nicknames: components["schemas"]["ViewportFeature"][];
            /** Bookmarks */
            bookmarks: components["schemas"]["ViewportFeature"][];
        };
        /** VoteRequest */
        VoteRequest: {
            /** Proposal Id */
            proposal_id: number;
            /** Value */
            value: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    search_places_api_search_get: {
        parameters: {
            query: {
                q: string;
                country?: string | null;
                broad?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_magic_link_api_auth_magic_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Writes are temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_session_api_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                namescape_guest?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Writes are temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                namescape_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_share_card_api_passport__username__card_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_profile_api_users__username__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_passport_api_passport__username__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassportResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_place_api_places__place_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                place_id: number;
            };
            cookie?: {
                namescape_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_etymology_api_places__place_id__etymology_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                place_id: number;
            };
            cookie?: {
                namescape_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionResponse"];
                };
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Refused */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Writes are temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_my_discoveries_api_discoveries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                namescape_session?: string | null;
                namescape_guest?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDiscoveriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_discovery_api_discoveries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                namescape_session?: string | null;
                namescape_guest?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryResponse"];
                };
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Refused */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An etymology is required first */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Writes are temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_puzzle_api_puzzle_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                namescape_session?: string | null;
                namescape_guest?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PuzzleStateResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    guess_puzzle_api_puzzle__puzzle_id__guess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                puzzle_id: number;
            };
            cookie?: {
                namescape_session?: string | null;
                namescape_guest?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PuzzleStateResponse"];
                };
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Writes are temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_puzzle_archive_api_puzzle_archive_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                namescape_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_scheduled_job_get_api_cron__job__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronResult"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_scheduled_job_api_cron__job__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronResult"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_viewport_api_viewport_get: {
        parameters: {
            query: {
                west: number;
                south: number;
                east: number;
                north: number;
                zoom: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                namescape_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_bookmark_api_bookmarks__place_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                place_id: number;
            };
            cookie?: {
                namescape_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Writes are temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_bookmark_api_bookmarks__place_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                place_id: number;
            };
            cookie?: {
                namescape_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Writes are temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_bookmarks_api_bookmarks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                namescape_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarksResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_proposal_api_proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                namescape_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalResponse"];
                };
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Refused */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Writes are temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cast_vote_api_votes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                namescape_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Writes are temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_contest_api_contests__place_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                place_id: number;
            };
            cookie?: {
                namescape_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContestBoard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_activity_api_activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                namescape_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
