import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  // schema.ts is generated by openapi-typescript; never hand-edited, never linted.
  { ignores: ['dist', 'src/api/schema.ts'] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: { ecmaVersion: 2023, globals: globals.browser },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // PRD 8.3: the globe module is the only place that knows MapLibre exists.
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/globe/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['maplibre-gl', 'maplibre-gl/*'],
              message: 'MapLibre may only be imported inside src/globe/.',
            },
          ],
        },
      ],
    },
  },
)
